// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:demo2/money_share/model/name_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GroupShareMoneyAdapter());
    registerAdapter(MoneyModelAdapter());
    registerAdapter(NameModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GroupShareMoneyAdapter());
    registerAdapter(MoneyModelAdapter());
    registerAdapter(NameModelAdapter());
  }
}
